### ISSUE TITLE
Device not showing on Tactical

### ISSUE THREAD

**Issue by RedGuilhas** [netvolt/LinuxRMM-Script#2]
I used this script to install the agent on a Linux machine. It's showing up on Mesh but not on Tactical.
Any step thay I may have skipped?

**Comment by Sarryaz** [comment]
Hey, I've had the same issue. You need to take a look at the log/output of the script, after the installation is finished, and troubleshoot from there. For my maschine "unzip" was missing, despite the installation showing "INFO[0006] Installation was successfull!".
Also, the script needs to output "INFO[0000] Adding agent to dashboard", otherwise the agent is not added in the dashboard of TRRM, but only to MeshCentral.

Hope this helps. :)

**Comment by RedGuilhas** [comment]
> 

Thank you! It was really the unzip missing. It's working now.
